version: "3"
services:
  front:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:3000
    tty: true
    command: sh -c 'npm start'
