version: "3"
services:
  db:
    image: mariadb:10.7
    container_name: db_mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
    - typing-game-network

  web:
    build: #ここをちゃんと書かないと、DockerfileのCOPYなどが上手く機能しない
      context: ./typing-game-api
      dockerfile: ./Dockerfile
    container_name: api-rails
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./typing-game-api:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - typing-game-network
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build: .
    container_name: front_react
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - typing-game-network
    tty: true
    command: sh -c 'npm start'

volumes:
  bundle-volume:
  db-data:

networks:
  typing-game-network:
    external: true
